name: GitHub 3D Contribution City

on:
  schedule:
    - cron: "0 18 * * *" # Har roz auto-refresh hoga
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D City Skyline
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: umairs759
      - name: Commit & Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "chore: update 3d contribution grid skyline" || exit 0
          git push
